#!/usr/bin/env python3
"""Produce a before/after diff report for every corpus cleaning change.

The "before" side is read from a git revision so the report stays reproducible after the
corpus file has been rebuilt in place. The "after" side is produced by re-running ingestion
against the pinned PDF.

Usage::

    python scripts/cleaning_report.py --before-ref HEAD --output docs/cleaning_report.md
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from ng12_rag.config import load_settings  # noqa: E402
from ng12_rag.ingestion import run_ingestion  # noqa: E402

# Each pattern is one defect class we assert is absent from the cleaned corpus.
ARTIFACT_PATTERNS: dict[str, re.Pattern[str]] = {
    "page_footer_url": re.compile(r"conditions#notice-of-rights", re.IGNORECASE),
    "notice_of_rights_prose": re.compile(r"Subject to Notice of rights", re.IGNORECASE),
    "copyright_line": re.compile(r"©\s*NICE", re.IGNORECASE),
    "page_x_of_y": re.compile(r"\bPage\s+\d+\s+of\b", re.IGNORECASE),
    "bare_page_total": re.compile(r"(?<![\d.])101\b"),
    "running_header": re.compile(r"Suspected cancer:\s*recognition and referral", re.IGNORECASE),
    "subsection_title_bleed": re.compile(
        r"\[(?:19|20)\d{2}\][\s,]+[A-Z][A-Za-z\- ]{3,40}\s*$"
    ),
}


def read_before(ref: str, path: str) -> dict[str, str]:
    """Return recommendation_id -> text from a committed corpus revision."""

    try:
        blob = subprocess.run(
            ["git", "show", f"{ref}:{path}"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout
    except subprocess.CalledProcessError as exc:
        raise SystemExit(f"Could not read {path} at {ref}: {exc.stderr.strip()}") from exc

    out: dict[str, str] = {}
    for line in blob.splitlines():
        if not line.strip():
            continue
        record = json.loads(line)
        out[record["metadata"]["recommendation_id"]] = record["text"]
    return out


def classify(text: str) -> list[str]:
    return [name for name, pattern in ARTIFACT_PATTERNS.items() if pattern.search(text)]


def first_difference(before: str, after: str) -> str:
    """Return a short window around the first differing character."""

    limit = min(len(before), len(after))
    index = next((i for i in range(limit) if before[i] != after[i]), limit)
    start = max(0, index - 70)
    return f"...{before[start:index + 90]}..."


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--before-ref", default="HEAD")
    parser.add_argument("--corpus-path", default="data/processed/chunks.jsonl")
    parser.add_argument("--config", type=Path, default=REPO_ROOT / "config/config.yaml")
    parser.add_argument("--output", type=Path, default=REPO_ROOT / "docs/cleaning_report.md")
    args = parser.parse_args()

    before = read_before(args.before_ref, args.corpus_path)
    after = {rec.recommendation_id: rec.text for rec in run_ingestion(load_settings(args.config))}

    changed = sorted(
        (rid for rid in after if rid in before and before[rid] != after[rid]),
        key=lambda r: [int(p) for p in r.split(".")],
    )
    residual = {rid: classify(text) for rid, text in after.items() if classify(text)}

    lines: list[str] = [
        "# Corpus Cleaning Report",
        "",
        "Generated by `scripts/cleaning_report.py`. The before side is the committed corpus at "
        f"`{args.before_ref}`; the after side is a fresh ingestion run against the pinned PDF.",
        "",
        "## Summary",
        "",
        f"- Recommendations in corpus: **{len(after)}**",
        f"- Recommendations whose text changed: **{len(changed)}**",
        f"- Recommendations with residual artifacts after cleaning: **{len(residual)}**",
        "",
        "### Defect classes swept",
        "",
        "| Class | Before | After |",
        "| --- | --- | --- |",
    ]
    for name, pattern in ARTIFACT_PATTERNS.items():
        n_before = sum(1 for t in before.values() if pattern.search(t))
        n_after = sum(1 for t in after.values() if pattern.search(t))
        lines.append(f"| `{name}` | {n_before} | {n_after} |")

    lines += [
        "",
        "Counts are recommendations affected, not total occurrences. The sweep runs over the "
        "whole corpus rather than only the records previously known to be affected.",
        "",
        "## Per-recommendation changes",
        "",
    ]

    if not changed:
        lines.append("No text changed.")
    for rid in changed:
        removed = sorted(set(classify(before[rid])) - set(classify(after[rid])))
        delta = len(before[rid]) - len(after[rid])
        lines += [
            f"### {rid}",
            "",
            f"- Artifact classes removed: {', '.join(f'`{r}`' for r in removed) or 'none'}",
            f"- Characters removed: {delta}",
            "",
            "Before (around first difference):",
            "",
            "```text",
            first_difference(before[rid], after[rid]),
            "```",
            "",
            "After (full cleaned text):",
            "",
            "```text",
            after[rid],
            "```",
            "",
        ]

    lines += ["## Residual artifacts", ""]
    if residual:
        lines.append("These still need attention:")
        lines.append("")
        for rid, classes in sorted(residual.items()):
            lines.append(f"- `{rid}`: {', '.join(classes)}")
    else:
        lines.append("None. Every defect class above sweeps clean across the full corpus.")
    lines.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {args.output} ({len(changed)} changed, {len(residual)} residual)")
    return 1 if residual else 0


if __name__ == "__main__":
    raise SystemExit(main())
